synced with Ubuntu packager

diff --git a/package-templates/elasticsearch-bootstrap.template b/package-templates/elasticsearch-bootstrap.template
--- a/package-templates/elasticsearch-bootstrap.template
+++ b/package-templates/elasticsearch-bootstrap.template
@@ -2,61 +2,61 @@
 
 function state_error
 {
-	echo "ERROR: ${1:-UNKNOWN} (status $?)" 1>&2
-	exit 1
+    echo "ERROR: ${1:-UNKNOWN} (status $?)" 1>&2
+    exit 1
 }
 
 function check_pkg
 {
-	echo "checking to see if package $1 is installed..."
-	dpkg -s $1 || state_error "package $1 is not installed"
-	echo "package $1 is installed"
+    echo "checking to see if package $1 is installed..."
+    dpkg -s $1 || state_error "package $1 is not installed"
+    echo "package $1 is installed"
 }
 
 function check_user
 {
-	echo "checking to see if user $1 exists..."
-	id -u $1 || state_error "user $1 doesn't exists"
-	echo "user $1 exists"
+    echo "checking to see if user $1 exists..."
+    id -u $1 || state_error "user $1 doesn't exists"
+    echo "user $1 exists"
 }
 
 function check_port
 {
-	echo "checking to see if port $1 is opened..."
-	nc -z $1 $2 || state_error "port $2 is closed"
-	echo "port $2 on $1 is opened"
+    echo "checking to see if port $1 is opened..."
+    nc -z $1 $2 || state_error "port $2 is closed"
+    echo "port $2 on $1 is opened"
 }
 
 function check_dir
 {
-	echo "checking to see if dir $1 exists..."
-	if [ -d $1 ]; then
-		echo "dir $1 exists"
-	else
-		state_error "dir $1 doesn't exist"
-	fi
+    echo "checking to see if dir $1 exists..."
+    if [ -d $1 ]; then
+        echo "dir $1 exists"
+    else
+        state_error "dir $1 doesn't exist"
+    fi
 }
 
 function check_file
 {
-	echo "checking to see if file $1 exists..."
-	if [ -f $1 ]; then
-		echo "file $1 exists"
-		# if [ -$2 $1 ]; then
-			# echo "$1 exists and contains the right attribs"
-		# else
-			# state_error "$1 exists but does not contain the right attribs"
-		# fi
-	else
-		state_error "file $1 doesn't exists"
-	fi
+    echo "checking to see if file $1 exists..."
+    if [ -f $1 ]; then
+        echo "file $1 exists"
+        # if [ -$2 $1 ]; then
+            # echo "$1 exists and contains the right attribs"
+        # else
+            # state_error "$1 exists but does not contain the right attribs"
+        # fi
+    else
+        state_error "file $1 doesn't exists"
+    fi
 }
 
 function check_upstart
 {
-	echo "checking to see if $1 daemon is running..."
-	sudo status $1 || state_error "daemon $1 is not running"
-	echo "daemon $1 is running"
+    echo "checking to see if $1 daemon is running..."
+    sudo status $1 || state_error "daemon $1 is not running"
+    echo "daemon $1 is running"
 }
 
 function check_service
@@ -139,6 +139,10 @@ curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage -d '
 echo "creating blueprint mapping..."
 curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/blueprint/_mapping -d '{"blueprint": {"properties": {"plan": {"enabled": false}}}}'
 echo "creating deployment mapping..."
-curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment/_mapping -d '{"deployment": {"properties": {"plan": {"enabled": false}}}}'
+curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment/_mapping -d '{"deployment": {"properties": {"plan": {"enabled": false}, "workflows": {"enabled": false}}}}'
+echo "creating node mapping..."
+curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node/_mapping -d '{ "node": { "_id": { "path": "id" }, "properties": { "types": { "type": "string", "index_name": "type" }, "properties": { "enabled": false } } } }'
+echo "creating node-instance mapping..."
+curl --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node_instance/_mapping -d '{ "node_instance": { "_id": { "path": "id" }, "properties": { "runtime_properties": { "enabled": false } } } }'
 echo "printing mappings..."
 curl --retry 5 --retry-delay 3 -XGET http://localhost:9200/cloudify_storage/_mapping?pretty=1
